main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('s_upload/<pk>', views.simple_upload, name='upload'),
    path('l_upload/<pk>', views.l_upload, name='l_upload'),
    path('square_with_small_image/<pk>', views.square_with_small_image, name='square_with_small_image'),
    path('vertical/<pk>', views.vertical_image, name='vertical_image'),
    
]

pillow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from storages.backends.s3boto3 import S3Boto3Storage

class Merged(models.Model):
    m_img = models.ImageField(default='d.png', upload_to='merged_pic')
    name = models.CharField(max_length=50, blank=False, default='')
    village = models.CharField(max_length=50, blank=False, default='')
    number = models.CharField(max_length=10, blank=False, default='')

    def __str__(self):
        return f'{self.id} merged'

O_CHOICES = (
    ('square','square'),
    ('landscape', 'landscape'),
    ('square_with_small_image', 'square_with_small_image'),
    ('vertical', 'vertical'),
)

class Frame(models.Model):
    frame = models.ImageField(default='d.png', upload_to='frames_pic')
    mask = models.ImageField(default='d.png', upload_to='mask_img')
    orientation = models.CharField(max_length=30, default='', choices=O_CHOICES)
    def __str__(self):
        return f'{self.id} frame'

class Uimg(models.Model):
    img = models.ImageField(default='d.png', upload_to='user_img')

    def __str__(self):
        return f'{self.id} user pic'

main/forms.py
from django import forms
from .models import Uimg
from django.core import validators


SITES = (
    ('  ', '    '),
    ('ડાભોર', 'ડાભોર'),
    ('તાંતિવેલા', 'તાંતિવેલા'),
    ('છાત્રોડા', 'છાત્રોડા'),
    ('ડારી', 'ડારી'),
    ('દેદા', 'દેદા'),
    ('પાલડી', 'પાલડી'),
    ('છાપરી', 'છાપરી'),
    ('હસ્નાવદર', 'હસ્નાવદર'),
    ('મલોંઢા', 'મલોંઢા'),
    ('ખેરાળી', 'ખેરાળી'),
    ('વાવડી', 'વાવડી'),
    ('ચમોડા ', 'ચમોડા'),
    ('સારસવા ', 'સારસવા'),
    ('કીંદરવા ', 'કીંદરવા'),
    )


from django.forms.widgets import NumberInput

class CustomIntegerField(forms.IntegerField):

    def __init__(self, *, max_value=None, min_value=None, **kwargs):
        self.max_value, self.min_value = max_value, min_value
        if kwargs.get('localize') and self.widget == NumberInput:
            # Localized number input is not well supported on most browsers
            kwargs.setdefault('widget', super().widget)
        super().__init__(**kwargs)

        if max_value is not None:
            self.validators.append(validators.MaxValueValidator(max_value, "Enter valid 10 digit mobile number."))
        if min_value is not None:
            self.validators.append(validators.MinValueValidator(min_value, "Enter valid 10 digit mobile number."))


class UimgForm(forms.Form):
    name = forms.CharField(required=False)
    # village = forms.ChoiceField(choices = SITES) 
    village = forms.CharField(required=False) 
    # number = forms.CharField(required=False)
    number = CustomIntegerField(min_value=1000000000, max_value=9999999999)
    img = forms.ImageField()
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(UimgForm, self).__init__(*args, **kwargs)
        self.fields['img'].label = "ફોટો પસંદ કરવા માટે નીચેનું બટન દબાવો"
        self.fields['name'].label = "તમારું નામ"
        self.fields['number'].label = "મોબાઇલ નંબર"
        self.fields['village'].label = "તમારું ગામ"

main/views.py
import os
from django.conf import settings
from django.shortcuts import render
from .models import Frame, Uimg, Merged
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from PIL import Image, ImageDraw, ImageFont, ImageOps
from .forms import UimgForm
from urllib.request import urlopen
import requests
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
import base64
from base64 import b64encode

def home(request):
    frames = Frame.objects.all().order_by('-pk')
    context = locals()
    return render(request, 'main/home.html', context)


def inhance_mask(mask):    
    inhance_mask_data = []
    mask_data = mask.getdata()
    for item in mask_data:
        if item[0] in list(range(0, 100)):
            inhance_mask_data.append((0, 0, 0))
        else:
            inhance_mask_data.append(item)

    mask.putdata(inhance_mask_data)
    mask = mask.convert('1')
    return mask



def simple_upload(request, pk):
    if request.method == 'POST':
        form = UimgForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES
            img = files.get("img")
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            w = form.cleaned_data.get('width')
            h = form.cleaned_data.get('height')
            name = form.cleaned_data.get('name')
            village = form.cleaned_data.get('village')
            number = form.cleaned_data.get('number')
            #nl = '\n'
            #info= f'Name: {name}{nl}Village: {village}'

            i_rgb = Image.open(img)
            if i_rgb.mode != "RGB":
                i_rgb.convert('RGB')
            i = ImageOps.exif_transpose(i_rgb)

            frame_img_obj = Frame.objects.filter(id=pk).first().frame.file
            mask_img_obj = Frame.objects.filter(id=pk).first().mask.file
            f = Image.open(frame_img_obj)
            m = Image.open(mask_img_obj).convert('L').resize(f.size)

            cropped_image = i.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((f.size), Image.ANTIALIAS)
            #thumb_io = BytesIO()
            #resized_image.save(thumb_io, format='PNG', quality=80)
            #inmemory_uploaded_file = InMemoryUploadedFile(thumb_io, None, 'user_img.png', 
            #                                 'image/png', thumb_io.tell(), None)
            #instance = Uimg()
            #instance.img = inmemory_uploaded_file
            #instance.save()


            if f.mode != "RGB":
                f.convert('RGB')

            #draw = ImageDraw.Draw(f)
            #draw.text((51, 51), info ,(255,255,255))

            f = Image.composite(resized_image, f, m)

            #f.paste(resized_image,(322,45))
            thumb_io = BytesIO()
            f.save(thumb_io, format='PNG', quality=80)
            encoded_img = base64.b64encode(thumb_io.getvalue())
            decoded_img = encoded_img.decode('utf-8')
            img_data = f"data:image/png;base64,{decoded_img}"
            #f_inmemory_uploaded_file = InMemoryUploadedFile(thumb_io, None, 'merge.png', 
            #                                 'image/png', thumb_io.tell(), None)
            f_instance = Merged()
            #f_instance.m_img = f_inmemory_uploaded_file
            f_instance.name = name
            f_instance.village = village
            f_instance.number = number
            f_instance.save()
    else:
        form = UimgForm()

    context = locals()
    return render(request, 'main/upload.html', context)


def l_upload(request, pk):
    if request.method == 'POST':
        form = UimgForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES
            img = files.get("img")
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            w = form.cleaned_data.get('width')
            h = form.cleaned_data.get('height')
            name = form.cleaned_data.get('name')
            village = form.cleaned_data.get('village')
            number = form.cleaned_data.get('number')
            nl = ' , '
            info= f'નામ: {name}{nl}ગામ: {village}'

            i_rgb = Image.open(img)
            if i_rgb.mode != "RGB":
                i_rgb.convert('RGB')
            i = ImageOps.exif_transpose(i_rgb)

            frame_img_obj = Frame.objects.filter(id=pk).first().frame.file
            mask_img_obj = Frame.objects.filter(id=pk).first().mask.file
            f = Image.open(frame_img_obj)
            m = Image.open(mask_img_obj).convert('RGB').resize(f.size)
            m = inhance_mask(m)
            cropped_image = i.crop((x, y, w+x, h+y))
            new = cropped_image.resize((358, 358), Image.ANTIALIAS)
            resized_image = Image.new('RGB', (f.size), color = (255, 255, 255))
            resized_image.paste(new, (77, 130))

            if f.mode != "RGB":
                f.convert('RGB')

            f = Image.composite(resized_image, f, m)
            # draw = ImageDraw.Draw(f)
            # fontsize = 20
            # font = ImageFont.truetype(os.path.join(settings.BASE_DIR, 'HindVadodara-Medium.ttf'), fontsize)
            # while font.getsize(info)[0] < 306:
            #     fontsize += 1
            #     font = ImageFont.truetype('HindVadodara-Medium.ttf',fontsize)  
            # draw.text((527, 497), info, fill =(52, 51, 140), font = font, align ="center") 

            thumb_io = BytesIO()
            f.save(thumb_io, format='PNG', quality=80)
            thumb_io = BytesIO()
            f.save(thumb_io, format='PNG', quality=80)
            encoded_img = base64.b64encode(thumb_io.getvalue())
            decoded_img = encoded_img.decode('utf-8')
            img_data = f"data:image/png;base64,{decoded_img}"

            f_instance = Merged()
            #f_instance.m_img = f_inmemory_uploaded_file
            f_instance.name = name
            f_instance.village = village
            f_instance.number = number
            f_instance.save()
    else:
        form = UimgForm()

    frame_img = Frame.objects.filter(id=pk).first()
    context = locals()
    return render(request, 'main/upload.html', context)


def square_with_small_image(request, pk):
    if request.method == 'POST':
        form = UimgForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES
            img = files.get("img")
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            w = form.cleaned_data.get('width')
            h = form.cleaned_data.get('height')
            name = form.cleaned_data.get('name')
            village = form.cleaned_data.get('village')
            number = form.cleaned_data.get('number')
            nl = ' , '
            info= f'નામ: {name}{nl}ગામ: {village}'

            i_rgb = Image.open(img)
            if i_rgb.mode != "RGB":
                i_rgb.convert('RGB')
            i = ImageOps.exif_transpose(i_rgb)

            frame_img_obj = Frame.objects.filter(id=pk).first().frame.file
            mask_img_obj = Frame.objects.filter(id=pk).first().mask.file
            f = Image.open(frame_img_obj)
            m = Image.open(mask_img_obj).convert('RGB').resize(f.size)
            m = inhance_mask(m)

            cropped_image = i.crop((x, y, w+x, h+y))
            new = cropped_image.resize((390, 390), Image.ANTIALIAS)
            resized_image = Image.new('RGB', (f.size), color = (255, 255, 255))
            resized_image.paste(new, (60, 370))

            if f.mode != "RGB":
                f.convert('RGB')

            #f = Image.composite(resized_image, f, m)

            f = Image.composite(resized_image, f, m)

            thumb_io = BytesIO()
            f.save(thumb_io, format='PNG', quality=80)
            encoded_img = base64.b64encode(thumb_io.getvalue())
            decoded_img = encoded_img.decode('utf-8')
            img_data = f"data:image/png;base64,{decoded_img}"

            f_instance = Merged()
            f_instance.name = name
            f_instance.village = village
            f_instance.number = number
            f_instance.save()
    else:
        form = UimgForm()

    frame_img = Frame.objects.filter(id=pk).first()
    context = locals()
    return render(request, 'main/upload.html', context)



def vertical_image(request, pk):
    print('vertical bitch')
    if request.method == 'POST':
        form = UimgForm(request.POST, request.FILES)
        if form.is_valid():
            files = request.FILES
            img = files.get("img")
            x = form.cleaned_data.get('x')
            y = form.cleaned_data.get('y')
            w = form.cleaned_data.get('width')
            h = form.cleaned_data.get('height')
            name = form.cleaned_data.get('name')
            village = form.cleaned_data.get('village')
            number = form.cleaned_data.get('number')
            nl = ' , '
            info= f'નામ: {name}{nl}ગામ: {village}'

            i_rgb = Image.open(img)
            if i_rgb.mode != "RGB":
                i_rgb.convert('RGB')
            i = ImageOps.exif_transpose(i_rgb)

            frame_img_obj = Frame.objects.filter(id=pk).first().frame.file
            mask_img_obj = Frame.objects.filter(id=pk).first().mask.file
            f = Image.open(frame_img_obj)
            m = Image.open(mask_img_obj).convert('RGB').resize(f.size)
            m = inhance_mask(m)
            cropped_image = i.crop((x, y, w+x, h+y))
            new = cropped_image.resize((600, 600), Image.ANTIALIAS)
            resized_image = Image.new('RGB', (f.size), color = (255, 255, 255))
            resized_image.paste(new, (80, 320))


main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}Vote For Hirabhai{% endblock %}</title>
    
    <link rel="stylesheet" href="{% static 'main/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Advanced-NavBar---Multi-dropdown.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" href="{% static 'main/assets/css/Lightbox-Gallery.css' %}">
    <link rel="stylesheet" href="{% static 'main/assets/css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'main/assets/css/Registration-Form-with-Photo.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'main/assets/css/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'main/assets/img/favicon.ico' %}"/>

  </head>
<body id="body">
      <div>
          <nav class="navbar navbar-light navbar-expand-md navigation-clean">
              <div class="container"><a class="navbar-brand" href="{% url 'home' %}"><img id="logo" src="{% static 'main/assets/img/congress PNG.png' %}" /></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                  <div class="collapse navbar-collapse"
                      id="navcol-1">
                      <ul class="nav navbar-nav ml-auto">
                      </ul>
                  </div>
              </div>
          </nav>
      </div>
      <hr id="hr">

{% block content %}{% endblock %}

    <script src="{% static 'main/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'main/assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'main/assets/js/Advanced-NavBar---Multi-dropdown.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>

{% block js %}{% endblock %}
<br><br><br>

<footer style="text-align: center; font-size: 12px; color: #71848a;">
    Developed By <a  target=”_blank” href="http://bit.ly/3VmKQWb"> Viraj Solanki</a>
</footer>
<br>
</body>

</html>

main/templates/main/home.html
    {% extends "main/base.html" %}
    {% block content %}

    <div id="main">
        <div id="head">
            <h1 id="step">🖼️</h1>
            <h1 id="time-to-show">કૃપા કરીને ફોટોફ્રેમ પસંદ કરો </h1>
            <h1 id="select-frame">Please select a photoframe</h1>
        </div>
        <div></div>
    </div>

    <div class="container mt-40">
        <div class="row mt-30">
 {% for i in frames %}
            <div class="col-md-4 col-sm-6">
                <div class="box14">
                {% if i.orientation == 'landscape' %}
                <a href="{% url 'l_upload' i.id %}">
                {% endif %}

                {% if i.orientation == 'square' %}
                <a href="{% url 'upload' i.id %}">
                {% endif %}

                {% if i.orientation == 'square_with_small_image' %}
                <a href="{% url 'square_with_small_image' i.id %}">
                {% endif %}


                {% if i.orientation == 'vertical' %}
                <a href="{% url 'vertical_image' i.id %}">
                {% endif %}


                    <img src="{{ i.frame.url }}" alt="">
                    <div class="box-content">
                    </div>
                </a>
                </div>
            </div>
{% endfor %}
            </div>
        </div>

  {% endblock content %}

main/templates/main/merged.html
<!DOCTYPE html>
<html lang="en">
<head>	
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pillow</title>

</head>
<body>
<h1>{{image2}}</h1>
{{merged_file_url}}
<img href="{{merged_file_url}}">

<h1>frame: {{frame}}</h1>
<br>
<h1>user img: {{user_img}}</h1>
</body>
</html>

main/templates/main/simple_upload.html
    {% extends "main/base.html" %}

    {% block content %}

        <!-- FORM TO UPLOAD THE IMAGES -->
        <form method="post" enctype="multipart/form-data" id="formUpload">
          {% csrf_token %}
          {{ form }}
        </form>

        <!-- MODAL TO CROP THE IMAGE -->
        <div class="modal fade" id="modalCrop">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Crop the photo</h4>
              </div>
              <div class="modal-body">
                <img src="" id="image" style="max-width: 100%;">
              </div>
              <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                  <button type="button" class="btn btn-default js-zoom-in">
                    <span class="glyphicon glyphicon-zoom-in"></span>
                  </button>
                  <button type="button" class="btn btn-default js-zoom-out">
                    <span class="glyphicon glyphicon-zoom-out"></span>
                  </button>
                </div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
              </div>
            </div>
          </div>
        </div>

        <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
        <h3> Selected frame </h3>
          {% if frame_img %}
            <img height="100%" src="{{ frame_img.frame.url }}">
          {% endif %}

        <h3> User Image </h3>
          {% if instance %}
            <img height="100%" src="{{ instance.img.url }}">
          {% endif %}
        <br>

        <h3> Merged Image </h3>
          {% if instance %}
            <img height="100%" src="{{ f_instance.m_img.url }}">
          {% endif %}
        <br>

    {% endblock content %}

    {% block js %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_img").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 173,
          minCropBoxHeight: 198,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      // Enable zoom in button
      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      // Enable zoom out button
      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });


      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

main/templates/main/upload.html
    {% extends "main/base.html" %}
    {% load crispy_forms_tags %}
    {% block content %}

          {% if img_data %}
    <div id="main">
        <div id="head">
            <h1 id="step">🙌 </h1>
            <h1 id="select-frame">તમારો ફોટો તૈયાર છે, <br>ડાઉનલોડ કરો અને શેર કરો</h1>
        </div>
        <div></div>
    </div>

       <div class="container mt-40">
            <div class="row mt-30">
                <div class="col-md-4 col-sm-6">
                    <div class="box14">
                        <img src="{{ img_data }}" alt="">
                    </div>
                    <div class="row">

                      <div class="col-md-12 col-sm-12 col-12">
                        <a href="{{ img_data }}" download="myphoto">
                        <button type="button" class="btn btn-primary btn-block download"> 
                        <i class="fa fa-download" aria-hidden="true"></i> ડાઉનલોડ કરો
                        </button>
                        </a>
                      </div>

                      <div class="col-md-12 col-sm-12 col-12">
                        <a href="{% url 'home' %}">
                        <button style="margin-top: 1rem;" type="button" class="btn btn-primary btn-block download"> 
                        <i class="fa fa-external-link" aria-hidden="true"></i> બીજો ફોટો બનાવો
                        </button>
                        </a>
                      </div>
                    </div>
                </div>

<script>
function download(url, filename) {
fetch(url).then(function(t) {
    return t.blob().then((b)=>{
        var a = document.createElement("a");
        a.href = URL.createObjectURL(b);
        a.setAttribute("download", filename);
        a.click();
    }
    );
});
}
</script>
            </div>
        </div>
          
          {% else %}

    <div id="main">
        <div id="head">
            <h1 id="step">📷</h1>
            <h1 id="time-to-show">તમારો ફોટો અને વિગતો અપલોડ કરો </h1>
            <h1 id="select-frame">Upload your photo and Details</h1>
        </div>
        <div></div>
    </div>

          <div class="register-photo">
              <div class="form-container">
                  <form method="post" enctype="multipart/form-data" id="formUpload">
                  {% csrf_token %}
                  {{ form|crispy }}
                  </form>
              </div>
          </div>

        <div class="container">
          <div class="row">
          <div class="col-md-4 col-sm-4 col-12"></div>
                      <div class="col-md-4 col-sm-4 col-12">
                        <a href="{% url 'home' %}">
                        <button type="button" class="btn btn-secondary btn-block"> 
                        <i class="fa fa-external-link" aria-hidden="true"> </i> એક અલગ ફ્રેમ પસંદ કરો
                        </button>
                        </a>
                      </div>
           <div class="col-md-4 col-sm-4 col-12"></div>
          </div>
          {% endif %}

        <!-- MODAL TO CROP THE IMAGE -->
        <div class="modal fade" id="modalCrop">
          <div class="modal-dialog">
            <div class="modal-content">
              <!---<div class="modal-header">
                <h4 class="modal-title">Crop the photo</h4>
              </div>-->
              <div class="modal-body">
                <img src="" id="image" style="max-width: 100%;">
              </div>
              <div class="modal-footer">
                <div class="btn-group pull-left" role="group">
                  <button type="button" class="btn btn-default js-zoom-in">
                    <span class="glyphicon glyphicon-zoom-in"></span>
                  </button>
                  <button type="button" class="btn btn-default js-zoom-out">
                    <span class="glyphicon glyphicon-zoom-out"></span>
                  </button>
                </div>
                <button type="button" class="btn btn-primary btn-block download js-crop-and-upload"> 
                        <i class="fa fa-upload" aria-hidden="true"> </i> અપલોડ કરો
                </button>
              </div>
            </div>
          </div>
        </div>

<!--<div class="container">
         CONTAINER TO DISPLAY THE CROPPED IMAGES 
        <h3> Selected frame </h3>
          {% if frame_img %}
            <img height="500px" src="{{ frame_img.frame.url }}">
          {% endif %}

        <h3> User Image </h3>
          {% if instance %}
            <img height="500px" src="{{ instance.img.url }}">
          {% endif %}
        <br>

        <h3> Merged Image </h3>
          {% if instance %}
            <img height="500px" src="{{ f_instance.m_img.url }}">
          {% endif %}
        <br>
</div> -->
    {% endblock content %}

    {% block js %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_img").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      // Enable zoom in button
      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      // Enable zoom out button
      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });


      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}